name: innetsect
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.0.2+20200115

environment:
  sdk: ">=2.6.0 <3.0.2"

dependencies:
  # 添加国际化，中文支持
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
    # 存储
  shared_preferences: ^0.5.4+5
  #sqlite数据库 
  sqflite: ^1.1.7+1
  provide: ^1.0.2
  dio: ^3.0.2
  rxdart: ^0.21.0
  flutter_screenutil: ^0.5.3
  video_player: ^0.10.2+3
  fluintl: ^0.1.3
  #用于iOS和Android的允许访问设备摄像头的Flutter插件。
  #camera: ^0.5.6
  json_serializable: ^3.2.2
  fluttertoast: ^3.0.4
  # 图片缓存
  cached_network_image: ^2.0.0-rc
  #cached_network_image: ^0.5.1
  flutter_swiper: ^1.1.6
  image_picker: ^0.6.1+4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  # 下拉listview
  flutter_easyrefresh: ^2.0.4
  # url_launcher
  url_launcher: ^5.2.1
  # webview
  #webview_flutter: ^0.3.15+1
  webview_flutter: ^0.3.19+3
  # 扫描二维码
  qrscan: ^0.2.17
  #加载
  flutter_spinkit: "^4.0.0"
  #html解析
  flutter_html: ^0.11.0
  # 支付宝支付
  tobias: ^1.2.0
  #城市选择器
  city_pickers: ^0.1.28
  #侧滑索引
  azlistview: ^0.1.2
  #转拼音
  lpinyin: ^1.0.7

  chewie: ^0.9.8+1
  flutter_webview_plugin: ^0.3.9+1
  qr_flutter: ^3.1.0
  #barcode_scan: ^1.0.0

  #微信支付
#  fluwx:fluwx ^1.1.3
  sy_flutter_wechat: ^0.2.2
  #获取设备信息
  device_info: ^0.4.1+2
  #获取版本信息
  package_info: ^0.4.0+11
  #阿里推送
  rammus: ^0.0.5
  #选择器
  flutter_picker: ^1.1.0
  #图片预览
  photo_view: ^0.9.0
  #百度地图
  flutter_baidu_map: ^0.0.5
  permission_handler: ^3.0.0
 

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/res/
    - assets/images/
    - assets/data/user.json

    - assets/images/ic_file_transfer.png
    - assets/images/ic_fengchao.png
    - assets/images/ic_tx_news.png
    - assets/images/ic_wx_games.png
    - assets/images/ic_new_friend.png
    - assets/images/ic_group_chat.png
    - assets/images/ic_tag.png
    - assets/images/ic_public_account.png
    - assets/images/ic_bottle_msg.png
    - assets/images/ic_feeds.png
    - assets/images/ic_game_entry.png
    - assets/images/ic_mini_program.png
    - assets/images/ic_people_nearby.png
    - assets/images/ic_quick_scan.png
    - assets/images/ic_quick_search.png
    - assets/images/ic_shake_phone.png
    - assets/images/ic_shopping.png
    - assets/images/ic_social_circle.png
    - assets/images/ic_wallet.png
    - assets/images/ic_album.png
    - assets/images/ic_collections.png
    - assets/images/ic_cards_wallet.png
    - assets/images/ic_emotions.png
    - assets/images/ic_settings.png
    - assets/images/ic_qrcode_preview_tiny.png
    - assets/images/default_nor_avatar.png

    - assets/images/star.png
    - assets/images/vip.png
    - assets/images/mars.png
    - assets/images/mars_big.jpg
    - assets/images/earth.png
    - assets/images/earth_big.jpg
    - assets/images/mercury.png
    - assets/images/mercury_big.jpg
    - assets/images/moon.png
    - assets/images/moon_big.jpg
    - assets/images/neptune.png
    - assets/images/neptune_big.jpg
    - assets/images/ic_gravity.png
    - assets/images/ic_distance.png
    - assets/images/logo.png
    - assets/images/yan_logo.png
    #底部导航Icon
    - assets/images/首页.png
    - assets/images/首页-选中.png
    - assets/images/品牌.png
    - assets/images/品牌选中.png
    - assets/images/活动选中.png
    - assets/images/活动.png
    - assets/images/购物车.png
    - assets/images/购物车选中.png
    - assets/images/我的.png
    - assets/images/我的选中.png
    - assets/images/erweima.png
    #二维码中间logo
    - assets/images/main/logo180x180.png


    #刷新图标
    - assets/images/icon_arrow.png
    - assets/images/icon_cry.png
    - assets/images/refresh.png
    #首页icon和图
    - assets/images/够买门票.png
    - assets/images/签到绑定.png
    - assets/images/排队扫码.png
    - assets/images/场馆地图.png
    - assets/images/l1.png
    - assets/images/l2.png
    - assets/images/关注.png
    - assets/images/我的页面背景图.png
    - assets/images/Logoy.png
    - assets/images/展会门票.png
    - assets/images/xiangxia.png
    - assets/images/y场馆地图.png
    - assets/images/my_ordered@3x.png
    #抽签
    - assets/images/中签.png
    - assets/images/未中签.png
    - assets/images/已过期.png

    #新个人中心icon
    - assets/images/newpersonalcentre/购物车@2x.png
    - assets/images/newpersonalcentre/我的卡券@2x.png
    - assets/images/newpersonalcentre/我的售后@2x.png
    - assets/images/newpersonalcentre/反馈意@2x.png
    - assets/images/newpersonalcentre/联系客服@2x.png
    - assets/images/newpersonalcentre/联系客服@3x.png
    - assets/images/newpersonalcentre/我的订单@2x.png
    - assets/images/newpersonalcentre/展会@2x.png
    - assets/images/newpersonalcentre/购买须知@2x.png
    - assets/images/newpersonalcentre/地址管理@2x.png
    - assets/images/newpersonalcentre/消息@1x.png
    - assets/images/yifi1.png
    - assets/images/yifu2.png
    - assets/images/chouqian.jpg
    - assets/images/registration_successful.jpg
    - assets/images/zhongqian.jpg

    #展会首页
    - assets/images/showhome/展会活动.png
    - assets/images/showhome/场馆地图.png
    - assets/images/showhome/购买门票.png
    - assets/images/showhome/展会商品.png
    - assets/images/showhome/签到绑定.png
    - assets/images/showhome/扫码购物.png
    # 默认展示图片
    - assets/images/default/default_squre_img.png
    - assets/images/default/default_img.png
    - assets/images/default/default_hori_img.png
    #已过期
    - assets/images/default/past.png
    # 预约列表背景
    - assets/images/default/activity_bg.png
    #已使用
    - assets/images/user/un_use.png
    #展会-我的-vipcard
    - assets/images/user/vipcard/vip_card.png
    #客服图标
    - assets/images/user/feedback.png
    # 我的按钮icon
    # 我的门票
    - assets/images/user/my_ticket@3x.png
    # 扫码签到
    - assets/images/user/my_scan@3x.png
    # 我的预约
    - assets/images/user/my_ordered@3x.png
    # 商城
    - assets/images/mall/welcome.png
    - assets/images/mall/bg.gif
    - assets/images/mall/hot_brand1.png
    - assets/images/mall/hot_brand2.png
    - assets/images/mall/hot_brand3.png
    - assets/images/mall/hot_brand4.png
    - assets/images/mall/hot_brand5.png
    - assets/images/mall/hot_brand6.png
    - assets/images/mall/logo.jpg
    - assets/images/mall/wechat.jpg
    - assets/images/mall/qq.jpg
    - assets/images/mall/weibo.jpg
    # ----商城底部导航----
    - assets/images/mall/tab_news.png
    - assets/images/mall/tab_news_h.png
    - assets/images/mall/tab_star.png
    - assets/images/mall/tab_star_h.png
    - assets/images/mall/tab_home.png
    - assets/images/mall/tab_home_h.png
    - assets/images/mall/tab_mall.png
    - assets/images/mall/tab_mall_h.png
    - assets/images/mall/tab_me.png
    - assets/images/mall/tab_me_h.png
    - assets/images/mall/brand@3x.png
    - assets/images/mall/sel_brand@3x.png
    # -------购物车默认图-----------
    - assets/images/mall/default_cart.png
    - assets/images/mall/msg.png
    - assets/images/mall/setting.png
    - assets/images/mall/me_header.png
    - assets/images/mall/arrow_down.png
    - assets/images/mall/arrow_right.png
    - assets/images/mall/exhibition.png
    - assets/images/mall/wish.png
    - assets/images/mall/wish_list.png
    - assets/images/mall/money.png
    - assets/images/mall/product1.png
    - assets/images/mall/product2.png
    - assets/images/mall/find.png
    # 策略----
    - assets/images/mall/zhengpin1.png
    - assets/images/mall/zhengpin2.png
    - assets/images/mall/zhengpin3.png
    # 下拉刷新图---
    - assets/images/mall/fresh.png
    # ---支付成功、失败--
    - assets/images/mall/pay_success.png
    - assets/images/mall/pay_fail.png
    # --- 我的 ---
    - assets/images/user/header.png
    - assets/images/user/logo.png
    # --- 开屏页 ---
    - assets/images/main/open_app.jpg
    - assets/images/main/commodity_enter.jpg
    - assets/images/main/trade_enter.jpg
    # --- 暂无数据 ---
    - assets/images/mall/no_data.png
    # ----
    - assets/images/mall/del.png
    - assets/images/mall/edit.png
    - assets/images/mall/share.png
    - assets/images/mall/calendar.png
    - assets/images/mall/circle_bucket.png
    - assets/images/mall/yellow_point.png
    - assets/images/mall/shop_bucket.png
    - assets/images/mall/order.png
    - assets/images/mall/order_h.png
    - assets/images/mall/top_buyer.jpg
    - assets/images/mall/money_pay.png
    - assets/images/mall/btn_new.png
    - assets/images/mall/mall_home.png
    - assets/images/mall/buy_ticket.png
    - assets/images/mall/exhibition_news.png
    - assets/images/mall/exhibition_products.png
    - assets/images/mall/exhibition_map.png
    - assets/images/mall/exhibition_map_info.png
    - assets/images/mall/location.png
    - assets/images/mall/service_online.png
    - assets/images/mall/add.png
    - assets/images/mall/minus.png
    - assets/images/mall/express.png
    - assets/images/mall/weibo_to_innersect.png
    - assets/images/mall/中签大.png
    # 客服
    - assets/images/mall/service_p_icon.png
    # 心愿单
    - assets/images/mall/wish_icon.png
    # 购物车
    - assets/images/mall/cart_icon.png

    # 动画
    - assets/images/sparkles.png

    # camara
    - assets/images/ic_no_image.png
    - assets/images/ic_shutter_1.png
    - assets/images/ic_switch_camera_3.png

    # 交友
    - assets/images/friend.png
    - assets/images/suround.png
    - assets/images/leisure.png
    - assets/images/discovery.png
    - assets/images/community.png
    - assets/images/def_head.png
    - assets/images/def_head_big.png
    - assets/images/search.png

    - assets/images/friend/1.png
    - assets/images/friend/2.png
    - assets/images/friend/3.png
    - assets/images/friend/4.png
    - assets/images/friend/5.png
    - assets/images/friend/6.png

    - assets/images/friend/add.png
    - assets/images/friend/face.png
    - assets/images/friend/voice.png

  fonts:
    - family: appIconFont
      fonts:
       - asset: assets/fonts/iconfont.ttf
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
